### ISSUE TITLE
Absent OUJS GH Auth

### ISSUE THREAD

**Issue by Martii** [sebaro/SaveTube#3]
I noticed your script didn't update on OpenUserJS.org *(OUJS)*... I also looked into your account and noticed that you don't seem to have GH auth to start the automatic import from GH to OUJS. This will also help if there are any issues that show up since OUJS source is out of sync with your repo here. To enable import after you add an authentication method of GH go to https://openuserjs.org/user/add/scripts and import it from your repository... a webhook is needed on the GH side to enable automatic sync also described on that url.

Please note I recently read a Google+ doc that claims it's going away, at least in some sites, which may affect your account on OUJS if Google ever does that. I do recommend adding a secondary authentication of GitHub *(GH)* to OUJS at https://openuserjs.org/user/preferences

Thanks for a moment of your time and killer script btw. :)

Marti Martz
Admin OpenUserJS.org

**Comment by sebaro** [comment]
What if I have two scripts on the same repository?

I didn't understand, what's going away?

Thanks for your help.

**Comment by Martii** [comment]
> What if I have two scripts on the same repository?

I have multiple scripts on [my UserScripts repo](/Martii/UserScripts)... OUJS will let you pick any/all of the `.user.js` and `.js` anywhere in the repo... say any script at  [oujs - Meta View](/Martii/UserScripts/tree/master/src/oujs/Meta%20View) can be imported. For automatic synchronizing, as long as the webhook is set up, GitHub and OUJS will automatically synchronize with OUJS thus alleviating [you of the chore of keeping up to date on OUJS](https://openuserjs.org/scripts/sebaro/ViewTube/issues/update_url_is_set_to_another_website_that_openuserjs.org#comment-1466f473a5e). :) I noticed you have your `@downloadURL` pointing to here on GH but if someone installs the script on OUJS and tries it out...without letting Greasemonkey, or equivalent .user.js engine update... then they may use the peer review system to down vote your script. Some users are impatient and/or inexperienced and it is best to cover all your available options... if you choose to do so.

> what's going away?

On some sites, but **not OUJS currently**, Google+ authentication is being discarded. Google is constantly changing their authentication methods and it **could** eventually affect OUJS logging in at some point. :\ A secondary authentication on OUJS could allow you to login, with a note to development to toggle it for you,  in the event the Google+ OAuth goes away... time will tell for sure on this. Again the choice is yours... I really enjoy using your script and it's gaining popularity in my circles. :)

**Comment by sebaro** [comment]
I don't understand the @downloadURL part of your message. How does that matter if is set to GH or OUJS?

I've added GitHub auth and made it default.

Thanks again for your help.

**Comment by Martii** [comment]
> How does that matter if is set to GH or OUJS?

Just means you are consolidating here on GH... that's fine too e.g. nothing wrong with that... but if you want OUJS source to be up to date in the event that someone tries your script there before Greasemonkey *(GM)* has a chance to update *(or even you reimporting it)* and then that someone down votes your script... that will be disappointing big time... you can enable the webhook that I mentioned in [the comment above](https://github.com/sebaro/SaveTube/issues/3#issue-98038120)... instructions are all on that page... on a desktop it is the third column... on a portable device it's near the bottom of that page.

**Comment by sebaro** [comment]
I've added the webhook, the scripts were updated on OUJS after the license metadata commit.

One more question: what is the script "flag" for? My script was flagged and I didn't see any reason why.

**Comment by Martii** [comment]
We don't have a "reason" yet... so I have no idea... when we have that I'll attempt reset everyones flags... might be a long time though... as we are still working on other areas at the moment. Long term patience please. :)

**Comment by Martii** [comment]
Could be a down vote too.

**Comment by sebaro** [comment]
The problem was that the script was removed from the scripts/main page. I had to remove it from my profile and re-upload it.

**Comment by Martii** [comment]
> The problem was that the script was removed from the scripts/main page.

I don't understand this part. What happened and when?

**Comment by sebaro** [comment]
Some time ago, after you've started the site. I was searching for my scripts and saw this was missing. On the account/profile page the script had a red line and "Flagged" text instead of the number of votes. (I'm not 100% sure)

What does the votes number grey line mean? It has shorter before you've cleared the flag.
What happens when a script is flagged?

For me is not very important the rating/votes. I just want my scripts to be available for those who want to use it and  if it's removed to be able to see the reason.

**Comment by Martii** [comment]
> What does the votes number grey line mean? It has shorter before you've cleared the flag.
What happens when a script is flagged?

[Some light reading for you](https://github.com/OpenUserJs/OpenUserJS.org/issues/288)

Anyhow... gotta run do other things... thanks for the `@license` key... makes it a little easier in adminstration and I hope you enjoy the webhook. :)

**Comment by Martii** [comment]
@sebaro 
What happened to you? How are you doing?

**Comment by sebaro** [comment]
I'm fine, thanks. How are you?

**Comment by Martii** [comment]
Doing well. Was wondering where my most used script went from OUJS. :)

**Comment by sebaro** [comment]
I need to know why an user down-votes a script.
I think it's wrong when somebody down-votes a script without opening an issue.

**Comment by Martii** [comment]
Well I think that was discussed on the long term agenda... might be that they just don't like it... but other sites don't require an issue tracker with their voting either... so the decision has to be weighed in and tackled.  We are constantly removing spammers and resetting things... just takes some time. This week I'm planning on trying to get the rest of the Unicode issues complete for those users that occasionally upload extended Unicode script names... I just don't want to have a bunch of downtime until things are feature rich.

At least I know where you are here for my personal benefit. :)

**Comment by sebaro** [comment]
I think "might be that they just don't like it" it's more like "it doesn't work for me so It must be broken and I won't bother asking for help".

**Comment by Martii** [comment]
I'll ponder on this a little bit more officially but the priority of giving a "nudge" to open an issue on a down vote only in a dialog is low priority at this time... plus we'll need to balance the unfairness to people that "do like it and it works" but don't get "nudged" to give praise. I don't see an issue from you with that yet. ;)  All I can do currently as Admin on the site is give recommendations related to this... I don't control other peoples browsing habits other than enforcing the base TOS which was a collaborative effort of the Establishing Owners, and initial creators *(Founders)*... I'm the newest team member on OUJS dev as well but we do have a structure that I have to abide by as well. We try our best to compromise when possible... other times it's just not feasible.

On a personal level you are missed! :)

P.S. I have seen on the other external site you publish to there isn't any reasons available for viewing... but I understand your silent protest... time heals all I think.

**Comment by sebaro** [comment]
I don't care about up-votes and praises, I just need to know why the down-vote, there must be a reason, software is not art.

Maybe instead of up/down votes you can use reviews/ratings with comments like on USO.

I don't understand the PS, GitHub is the only site I have my scripts published to.

**Comment by Martii** [comment]
> I just need to know why the down-vote, there must be a reason, software is not art.

I'll see what I can when we get to that point. I agree art isn't in the nature normally... I had to guess, which is an art by opening a dialog, why you disappeared off of OUJS all of the sudden. You have the benefit of some one-on-one here because I enjoy your capabilities and efforts... I usually wouldn't spend this much time on a script author if I wasn't interested... officially I have a priority queue to attend to... which I'm doing in between these comments, sleep, work, etc.

> GitHub is the only site I have my scripts published to.

Hmm well that appears to make things more complicated... [the other guy](https://greasyfork.org/en/scripts/2983) . GPL *(and we do too)* allows derivatives but that's a flat out copy there I think. Wouldn't be the first time that site copied OUJS though.

**Comment by sebaro** [comment]
There are already requests like mine:
https://github.com/OpenUserJs/OpenUserJS.org/issues/286
Looking at the responses I doubt the system will change.

I've had my scripts on GreasyFork too but I've deleted them because they remove the update/download URLs from the code. I can't stop people to upload my scripts to any sites they like as long they keep the licence.

Thanks for your time, you don't have to waste it with me.

**Comment by Martii** [comment]
> I doubt the system will change.

I'm well aware of what's been typed before... I am a maintainer... the "nudge" on voting is about all I can suggest at this point... and that's blocked currently.

> you don't have to waste it with me.

I'll be doing other things as well as I've done for decades of my life.

This is an observation only... but the perceived defeatist attitude doesn't suit you well. I came back here because you artfully withdrew and I artfully asked you where you went. 

Development is also understanding in which we've provided each other with some food for thought as that phrase goes. The only idea I can think of in the moment is a "nudge" to create an issue... if that isn't good enough for you then that's that... but I'll keep your use case in mind if there is an epiphany on UI interaction. Some sort of balance needs to be achieved.
Forcing someone to fill out an issue form has a consequence of that you won't get any vote period. 

Doing USO style has a consequence of unneeded complexity and possible misuse of it... and definitely was a part of their retirement. 

The current issue system is simple, clean, and effective so far... the current voting system is simple, clean, and effective so far... what **you** do with it is up to you. Downvotes caring and upvote non-caring is your view. My perspective is ... some will, some won't, so what... with my scripts... if it happens it happens, if it doesn't it doesn't... I'll still keep plugging away best as I can instead of mulling over something that isn't shared by everyone.

Anyhow... I'll leave you be... I've said all I need to say at this time... if you think of a new idea please feel free to open one or just hide out here... I'll come join you if I have an issue with the Userscript. Try to keep your chin up. You are a capable programmer and you have brought some more thought to my processes. :)

**Comment by sebaro** [comment]
I appreciate your good words towards my work.
