### ISSUE TITLE
how to implement getLinks function for youtube

### ISSUE THREAD

**Issue by atheroth** [sebaro/SaveTube#5]
I am writing a similar script in php. I read the whole page (https://www.youtube.com/watch?v=s-MUzvASr8s) and check for video url patterns. I get nothing. How are you getting video url's? Let me know if a simple function can be written that returns at least one video download link for a given page (https://www.youtube.com/watch?v=s-MUzvASr8s). Thanks

**Comment by sebaro** [comment]
There are two ways to get the video streams:

1. video page:
Non-DASH: "url_encoded_fmt_stream_map":\s*"(.*?)"
DASH: "adaptive_fmts":\s*"(.*?)"

2. video info page https://www.youtube.com/get_video_info?video_id=s-MUzvASr8s
Non-DASH: url_encoded_fmt_stream_map=(.*?)&
DASH: adaptive_fmts=(.*?)&

Then you have to parse each video stream by its "itag" parameter:
https://en.wikipedia.org/wiki/Youtube#Quality_and_formats

**Comment by atheroth** [comment]
Thank you. This is super helpful. I'll close this issue now. I'll ask through your website if i need help again. That seems more appropriate. Thanks again!
